### PR TITLE
Restructure

### PR DESCRIPTION
**Pull request by 000JustMe**
I was kinda board so decide to commit to your project. Any issues or features you want to add let me know.

### CODE REVIEW

**Comment by 000JustMe** [comment]
Me and a mate built the most recent version

**Comment by WillRazorFace** [comment]
I have not yet seen all the modifications made, I have to take the time to check them out. I'm very busy right now, dude. I think I'll do an update on "Encrypt.py", "Decrypt.py" and "Rain.exe" tomorrow. I am now wanting to build the graphical interface that will be used to pass information such as virtual wallet to be paid, remaining time until the files are deleted and so on. I do not know if you are still interested in helping, but please answer me when you can, we should talk on Skype, Discord or something. See you.

**Comment by 000JustMe** [comment]
Building a GUI is not a problem. The virtual wallet stuff (depending on how advanced you need to be my be) may be more of a challenge. If you want Rain to be able to decrypt files after a payment or some other condition is verified then a server will almost certainly be needed to manage keys and verify payments. A HTTP server is the easiest to implement and will probably make the most sense as it can implement a simple API. 
I'd recommend you try to understand what has already been written, then come up with a design for the GUI and payment system that can then be built and tested.
If there is anything you don't understand about the code or any other complexities of the project don't be afraid to say.
If you want to talk on Skype or Discord just send me the details.

**Comment by WillRazorFace** [comment]
Yes, I plan to put this all in the project (GUI, decryption function after payment, etc). I think it will take a while because I lack the time to work correctly on this project and I do not understand the contents well (Tkinter, decryption by the server, etc). I'm sorry but I've updated the repository before checking any changes made by you. When you can read the README and check the Source Code folder. I put most of the functions in a separate file to, I think, facilitate understanding. I think I'm not using the right resources because the code seems a bit polluted.

**Comment by 000JustMe** [comment]
If you wish not to use any of my code, I cannot contribute to your project any further. For the moment your current classes are not clear enough to work with. In the rewrite some of your code and basic structure was salvaged and integrated but most was just not "usable". Also with the current code it will be difficult to integrate the count down, payment, decryption features "well". If you look at my version you will see what I mean.

**Pull request closed without merging**
